# Generated by Django 2.2.1 on 2020-10-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Donor', '공여자'), ('recipient', '수혜자')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('b_type', models.CharField(choices=[('A', 'A형'), ('B', 'B형'), ('AB', 'AB형'), ('O', 'O형'), ('Weak-A', 'Weak-A형'), ('Weak-B', 'Weak-B형'), ('RH-', 'RH-형'), ('RH+', 'RH+형'), ('Cis-AB', 'Cis-AB형'), ('MkMk', 'MkMk형')], max_length=50)),
                ('body', models.TextField()),
                ('region', models.CharField(choices=[('Gangwon', '강원'), ('Gyeonggi', '경기'), ('Gyeongnam', '경남'), ('Gyeongbuk ', '경북'), ('Gwangju', '광주'), ('Daegu', '대구'), ('Busan', '부산'), ('Seoul ', '서울'), ('Incheon', '인천'), ('Jeonnam', '전남'), ('Jeonbuk', '전북'), ('Jeju', '제주'), ('Chungnam', '충남'), ('Chungbuk', '충북')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
